title = "Rutger Blom Photography"
languageCode = "en"
languageName = "English"
weight = 1

[params.author]
name = "Rutger Blom"
image = "img/author.jpg"
headline = "Amateur Photographer"
#bio = ""
links = [
  { flickr = "https://flickr.com/people/rutgerblom" }
]