title = "My awesome website"

[params.author]
name = "Rutger Blom"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { linkedin = "https://linkedin.com/in/rutgerblom" }
]