title = "rutgerblom.github.io"

[params.author]
name = "Rutger Blom"
image = "img/author.jpg"
headline = "Amateur Photographer"
#bio = ""
links = [
  { flickr = "https://flickr.com/people/rutgerblom" }
]