title = "rutgerblom.github.io"

[params.author]
name = "Rutger Blom"
image = "img/author.png"
headline = "Amateur Photographer"
#bio = ""
links = [
  { flickr = https://flickr.com/photos/rutgerblom }
]