title = "rutgerblom.github.io"

[params.author]
name = "Rutger Blom"
image = "img/author.jpg"
headline = "Senior Consultant"
bio = "A little bit about me"
links = [
  { linkedin = "https://linkedin.com/in/rutgerblom" },
  { github = "https://github.com/rutgerblom" }
]