[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

#[[main]]
#  name = "Topics"
#  pageRef = "topics"
#  weight = 20

[[main]]
  pre = "flickr"
  name = "Flickr"
  url = "https://linkedin.com/in/rutgerblom"
  weight = 30

#[[footer]]
#  name = "Privacy"

