[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

#[[main]]
#  name = "Topics"
#  pageRef = "topics"
#  weight = 20

[[main]]
  pre = "Flickr"
  name = "LinkedIn"
  url = "https://flickr.com/photos/rutgerblom/"
  weight = 30

#[[footer]]
#  name = "Privacy"

